package dev.yazidcv.candidate;
import dev.yazidcv.identity.TenantContext; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.data.domain.*; import org.springframework.http.*; import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken; import org.springframework.web.bind.annotation.*; import java.time.Instant; import java.util.*;
@RestController @RequestMapping("/api/v1/candidates") public class CandidateController{
 private final CandidateRepository repo; private final TenantContext tenant; public CandidateController(CandidateRepository r,TenantContext t){repo=r;tenant=t;}
 @GetMapping public Page<CandidateResponse> list(@RequestParam(defaultValue="")String q,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")@Max(100)int size,JwtAuthenticationToken auth){UUID org=tenant.organizationId(auth);Pageable p=PageRequest.of(Math.max(page,0),size,Sort.by(Sort.Direction.DESC,"updatedAt"));return (q.isBlank()?repo.findByOrganizationIdAndActiveTrue(org,p):repo.search(org,q.trim(),p)).map(CandidateResponse::from);}
 @GetMapping("/{id}") public CandidateResponse get(@PathVariable UUID id,JwtAuthenticationToken auth){return CandidateResponse.from(find(id,auth));}
 @PostMapping public ResponseEntity<CandidateResponse> create(@Valid @RequestBody CandidateRequest req,JwtAuthenticationToken auth){var c=new Candidate(tenant.organizationId(auth),req.firstName(),req.lastName());apply(c,req);return ResponseEntity.status(HttpStatus.CREATED).body(CandidateResponse.from(repo.save(c)));}
 @PutMapping("/{id}") public CandidateResponse update(@PathVariable UUID id,@Valid @RequestBody CandidateRequest req,JwtAuthenticationToken auth){var c=find(id,auth);apply(c,req);return CandidateResponse.from(repo.save(c));}
 @DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void archive(@PathVariable UUID id,JwtAuthenticationToken auth){var c=find(id,auth);c.archive();repo.save(c);}
 private Candidate find(UUID id,JwtAuthenticationToken auth){return repo.findByIdAndOrganizationId(id,tenant.organizationId(auth)).orElseThrow(()->new NoSuchElementException("Candidate not found"));}
 private void apply(Candidate c,CandidateRequest r){c.update(r.firstName(),r.lastName(),r.email(),r.phone(),r.currentTitle(),r.currentCompany(),r.city(),r.country(),r.yearsExperience(),r.status(),r.professionalSummary(),r.skills());}
 public record CandidateRequest(@NotBlank String firstName,@NotBlank String lastName,@Email String email,String phone,@NotBlank String currentTitle,String currentCompany,String city,String country,@Min(0)@Max(80)int yearsExperience,@NotBlank String status,String professionalSummary,@NotNull List<@NotBlank String> skills){}
 public record CandidateResponse(UUID id,String firstName,String lastName,String fullName,String initials,String email,String phone,String currentTitle,String currentCompany,String city,String country,int yearsExperience,String status,String source,String professionalSummary,List<String> skills,int matchScore,String linkedinUrl,String githubUrl,List<String> spokenLanguages,String educationSummary,String experienceSummary,String projectsSummary,int extractionConfidence,Instant createdAt,Instant updatedAt){static CandidateResponse from(Candidate c){String initials=(c.getFirstName().substring(0,1)+c.getLastName().substring(0,1)).toUpperCase();return new CandidateResponse(c.getId(),c.getFirstName(),c.getLastName(),c.getFirstName()+" "+c.getLastName(),initials,c.getEmail(),c.getPhone(),c.getCurrentTitle(),c.getCurrentCompany(),c.getCity(),c.getCountry(),c.getYearsExperience(),c.getStatus(),c.getSource(),c.getProfessionalSummary(),c.getSkills(),c.getMatchScore(),c.getLinkedinUrl(),c.getGithubUrl(),c.getSpokenLanguages(),c.getEducationSummary(),c.getExperienceSummary(),c.getProjectsSummary(),c.getExtractionConfidence(),c.getCreatedAt(),c.getUpdatedAt());}}
}
