package dev.yazidcv.candidate;
import dev.yazidcv.cv.*;import dev.yazidcv.identity.TenantContext;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.data.domain.*;import org.springframework.http.*;import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken;import org.springframework.web.bind.annotation.*;import java.time.Instant;import java.util.*;import java.util.stream.Collectors;
@RestController @RequestMapping("/api/v1/candidates") public class CandidateController{
 private final CandidateRepository repo;private final TenantContext tenant;private final CandidateErasureService erasure;private final JobMatchScoringService scoring;private final CvDocumentRepository documents;
 public CandidateController(CandidateRepository r,TenantContext t,CandidateErasureService erasure,JobMatchScoringService scoring,CvDocumentRepository documents){repo=r;tenant=t;this.erasure=erasure;this.scoring=scoring;this.documents=documents;}
 @GetMapping public Page<CandidateResponse> list(@RequestParam(defaultValue="")String q,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")@Max(100)int size,JwtAuthenticationToken auth){UUID org=tenant.organizationId(auth);Pageable p=PageRequest.of(Math.max(page,0),size,Sort.by(Sort.Direction.DESC,"updatedAt"));Page<Candidate> result=q.isBlank()?repo.findByOrganizationIdAndActiveTrue(org,p):repo.search(org,q.trim(),p);var openings=scoring.openJobs(org);var ids=result.getContent().stream().map(Candidate::getId).toList();Map<UUID,List<CvDocument>> attachments=ids.isEmpty()?Map.of():documents.findAllByOrganizationIdAndCandidateIdIn(org,ids).stream().collect(Collectors.groupingBy(CvDocument::getCandidateId));return result.map(c->response(c,openings,attachments.getOrDefault(c.getId(),List.of())));}
 @GetMapping("/{id}") public CandidateResponse get(@PathVariable UUID id,JwtAuthenticationToken auth){var c=find(id,auth);return response(c,scoring.openJobs(c.getOrganizationId()),documents.findAllByOrganizationIdAndCandidateId(c.getOrganizationId(),c.getId()));}
 @PostMapping public ResponseEntity<CandidateResponse> create(@Valid @RequestBody CandidateRequest req,JwtAuthenticationToken auth){var c=new Candidate(tenant.organizationId(auth),req.firstName(),req.lastName());apply(c,req);c=repo.save(c);return ResponseEntity.status(HttpStatus.CREATED).body(response(c,scoring.openJobs(c.getOrganizationId()),List.of()));}
 @PutMapping("/{id}") public CandidateResponse update(@PathVariable UUID id,@Valid @RequestBody CandidateRequest req,JwtAuthenticationToken auth){var c=find(id,auth);apply(c,req);c=repo.save(c);return response(c,scoring.openJobs(c.getOrganizationId()),documents.findAllByOrganizationIdAndCandidateId(c.getOrganizationId(),c.getId()));}
 @DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void archive(@PathVariable UUID id,JwtAuthenticationToken auth){var c=find(id,auth);c.archive();repo.save(c);}
 @DeleteMapping("/{id}/permanent") @ResponseStatus(HttpStatus.NO_CONTENT) @org.springframework.security.access.prepost.PreAuthorize("hasRole('ADMIN')") public void erase(@PathVariable UUID id,JwtAuthenticationToken auth)throws java.io.IOException{erasure.erase(tenant.organizationId(auth),id);}
 private Candidate find(UUID id,JwtAuthenticationToken auth){return repo.findByIdAndOrganizationId(id,tenant.organizationId(auth)).orElseThrow(()->new NoSuchElementException("Candidate not found"));}
 private void apply(Candidate c,CandidateRequest r){c.update(r.firstName(),r.lastName(),r.email(),r.phone(),r.currentTitle(),r.currentCompany(),r.city(),r.country(),r.yearsExperience(),r.status(),r.professionalSummary(),r.skills());}
 private CandidateResponse response(Candidate c,List<dev.yazidcv.job.JobOpening> openings,List<CvDocument> cvs){var matches=scoring.scoreAll(c,openings);int best=matches.isEmpty()?0:matches.getFirst().score();String initials=(c.getFirstName().substring(0,1)+c.getLastName().substring(0,1)).toUpperCase();var attachments=cvs.stream().map(CvAttachment::from).toList();return new CandidateResponse(c.getId(),c.getFirstName(),c.getLastName(),c.getFirstName()+" "+c.getLastName(),initials,c.getEmail(),c.getPhone(),c.getCurrentTitle(),c.getCurrentCompany(),c.getCity(),c.getCountry(),c.getYearsExperience(),c.getStatus(),c.getSource(),c.getProfessionalSummary(),c.getSkills(),best,matches,attachments,c.getLinkedinUrl(),c.getGithubUrl(),c.getSpokenLanguages(),c.getEducationSummary(),c.getExperienceSummary(),c.getProjectsSummary(),c.getExtractionConfidence(),c.getCreatedAt(),c.getUpdatedAt());}
 public record CandidateRequest(@NotBlank String firstName,@NotBlank String lastName,@Email String email,String phone,@NotBlank String currentTitle,String currentCompany,String city,String country,@Min(0)@Max(80)int yearsExperience,@NotBlank String status,String professionalSummary,@NotNull List<@NotBlank String> skills){}
 public record CvAttachment(UUID id,String filename,String contentType,long fileSize,String status,Instant uploadedAt){static CvAttachment from(CvDocument d){return new CvAttachment(d.getId(),d.getOriginalFilename(),d.getContentType(),d.getFileSize(),d.getStatus(),d.getCreatedAt());}}
 public record CandidateResponse(UUID id,String firstName,String lastName,String fullName,String initials,String email,String phone,String currentTitle,String currentCompany,String city,String country,int yearsExperience,String status,String source,String professionalSummary,List<String> skills,int matchScore,List<JobMatchScoringService.JobMatch> jobMatches,List<CvAttachment> attachments,String linkedinUrl,String githubUrl,List<String> spokenLanguages,String educationSummary,String experienceSummary,String projectsSummary,int extractionConfidence,Instant createdAt,Instant updatedAt){}
}
