package dev.yazidcv.candidate;
import dev.yazidcv.job.*;import org.springframework.stereotype.Service;import java.text.Normalizer;import java.util.*;import java.util.stream.Collectors;
@Service public class JobMatchScoringService{
 private static final Set<String> STOP=Set.of("senior","junior","lead","the","and","for","de","du","des","et","en","un","une","engineer","ingenieur","developer","developpeur");
 private final JobRepository jobs;public JobMatchScoringService(JobRepository jobs){this.jobs=jobs;}
 public List<JobOpening> openJobs(UUID organizationId){return jobs.findAllByOrganizationIdAndStatusOrderByUpdatedAtDesc(organizationId,"OPEN");}
 public List<JobMatch> scoreAll(Candidate c){return scoreAll(c,openJobs(c.getOrganizationId()));}
 public List<JobMatch> scoreAll(Candidate c,List<JobOpening> openings){return openings.stream().map(j->score(c,j)).sorted(Comparator.comparingInt(JobMatch::score).reversed().thenComparing(JobMatch::jobTitle)).toList();}
 JobMatch score(Candidate c,JobOpening j){Map<String,String> candidateSkills=c.getSkills().stream().collect(Collectors.toMap(this::normalizeSkill,s->s,(a,b)->a,LinkedHashMap::new));List<String> required=j.getRequiredSkills();List<String> matched=required.stream().filter(r->candidateSkills.containsKey(normalizeSkill(r))).toList();List<String> missing=required.stream().filter(r->!candidateSkills.containsKey(normalizeSkill(r))).toList();int skillScore=required.isEmpty()?35:(int)Math.round(70.0*matched.size()/required.size());Set<String> candidateTitle=tokens(c.getCurrentTitle()),jobTitle=tokens(j.getTitle());long titleHits=jobTitle.stream().filter(candidateTitle::contains).count();int titleScore=jobTitle.isEmpty()?0:(int)Math.round(20.0*titleHits/jobTitle.size());boolean remote="REMOTE".equalsIgnoreCase(j.getWorkplaceType()),sameLocation=c.getCity()!=null&&j.getLocation()!=null&&normalize(j.getLocation()).contains(normalize(c.getCity()));int locationScore=remote||sameLocation?10:0;int total=Math.min(100,skillScore+titleScore+locationScore);String explanation=matched.size()+" of "+required.size()+" required skills matched; title relevance "+titleScore+"/20; "+(remote?"remote role":sameLocation?"location aligned":"location not aligned");return new JobMatch(j.getId(),j.getTitle(),j.getDepartment(),j.getLocation(),j.getWorkplaceType(),total,skillScore,titleScore,locationScore,matched,missing,explanation);}
 private Set<String> tokens(String value){if(value==null)return Set.of();return Arrays.stream(normalize(value).split("[^a-z0-9+#.]+" )).filter(x->x.length()>1&&!STOP.contains(x)).collect(Collectors.toSet());}
 private String normalizeSkill(String s){String n=normalize(s).replace(".js","").replaceAll("[ ._-]","");return switch(n){case "dotnet","net"->".net";case "postgres"->"postgresql";case "js"->"javascript";case "ts"->"typescript";default->n;};}
 private String normalize(String s){return Normalizer.normalize(Objects.requireNonNullElse(s,""),Normalizer.Form.NFD).replaceAll("\\p{M}","").toLowerCase(Locale.ROOT).trim();}
 public record JobMatch(UUID jobId,String jobTitle,String department,String location,String workplaceType,int score,int skillScore,int titleScore,int locationScore,List<String> matchedSkills,List<String> missingSkills,String explanation){}
}
