package dev.yazidcv.job;
import dev.yazidcv.identity.TenantContext; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.data.domain.*; import org.springframework.http.*; import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken; import org.springframework.web.bind.annotation.*; import java.time.*; import java.util.*;
@RestController @RequestMapping("/api/v1/jobs") public class JobController{
 private final JobRepository repo; private final TenantContext tenant; public JobController(JobRepository r,TenantContext t){repo=r;tenant=t;}
 @GetMapping public Page<JobResponse> list(@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,JwtAuthenticationToken auth){return repo.findByOrganizationId(tenant.organizationId(auth),PageRequest.of(page,Math.min(size,100),Sort.by(Sort.Direction.DESC,"updatedAt"))).map(JobResponse::from);}
 @PostMapping public ResponseEntity<JobResponse> create(@Valid @RequestBody JobRequest r,JwtAuthenticationToken auth){var j=new JobOpening(tenant.organizationId(auth),r.title());apply(j,r);return ResponseEntity.status(201).body(JobResponse.from(repo.save(j)));}
 @PutMapping("/{id}") public JobResponse update(@PathVariable UUID id,@Valid @RequestBody JobRequest r,JwtAuthenticationToken auth){var j=repo.findByIdAndOrganizationId(id,tenant.organizationId(auth)).orElseThrow(()->new NoSuchElementException("Job not found"));apply(j,r);return JobResponse.from(repo.save(j));}
 private void apply(JobOpening j,JobRequest r){j.update(r.title(),r.department(),r.location(),r.workplaceType(),r.description(),r.requiredSkills(),r.status(),r.closingDate());}
 public record JobRequest(@NotBlank String title,String department,String location,String workplaceType,String description,@NotNull List<String> requiredSkills,@Pattern(regexp="DRAFT|OPEN|PAUSED|CLOSED|ARCHIVED")String status,LocalDate closingDate){}
 public record JobResponse(UUID id,String title,String department,String location,String workplaceType,String description,List<String> requiredSkills,String status,int candidateCount,LocalDate closingDate,Instant updatedAt){static JobResponse from(JobOpening j){return new JobResponse(j.getId(),j.getTitle(),j.getDepartment(),j.getLocation(),j.getWorkplaceType(),j.getDescription(),j.getRequiredSkills(),j.getStatus(),j.getCandidateCount(),j.getClosingDate(),j.getUpdatedAt());}}
}
