import { cloneElement, FormEvent, isValidElement, useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { useLocation, useNavigate } from 'react-router-dom'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis } from 'recharts'
import {
  Activity, ArrowLeft, ArrowRight, BarChart3, Bell, BriefcaseBusiness, Check, ChevronDown, ChevronRight,
  ChevronsUpDown, CircleAlert, CircleHelp, Clock3, Command, Download, FileCheck2, FileText, Filter,
  Languages, LayoutDashboard, LoaderCircle, LogOut, Menu, MoreHorizontal, Plus, RefreshCw, Search, Settings, ShieldCheck,
  Sparkles, Upload, UsersRound, X, Zap,
} from 'lucide-react'
import { api, Candidate, CvDocument, Dashboard as DashboardData, IntegrationStatus, Job, Review, session, User } from './api'
import { getLocale, Locale, setLocale, tr } from './i18n'
import AdminPage from './AdminPage'

type ResourceState = { dashboard: DashboardData | null; candidates: Candidate[]; jobs: Job[]; reviews: Review[]; cvs: CvDocument[]; integrations: IntegrationStatus[] }
const empty: ResourceState = { dashboard: null, candidates: [], jobs: [], reviews: [], cvs: [], integrations: [] }
const paths = ['/dashboard','/candidates','/jobs','/search','/uploads','/review','/reports','/settings','/admin'] as const
type Path = typeof paths[number]
const nav = [
  { items: [{ path: '/dashboard' as Path, label: 'Overview', icon: LayoutDashboard }] },
  { section: 'Recruitment', items: [{ path: '/candidates' as Path, label: 'Candidates', icon: UsersRound }, { path: '/jobs' as Path, label: 'Jobs', icon: BriefcaseBusiness }, { path: '/search' as Path, label: 'Talent search', icon: Search }] },
  { section: 'CV intelligence', items: [{ path: '/uploads' as Path, label: 'CV uploads', icon: Upload }, { path: '/review' as Path, label: 'Review queue', icon: FileCheck2 }, { path: '/reports' as Path, label: 'Reports', icon: BarChart3 }, { path: '/settings' as Path, label: 'Settings', icon: Settings }, { path: '/admin' as Path, label: 'Administration', icon: UsersRound }] },
]

export default function App() {
  const [user, setUser] = useState<User | null>(session.user())
  const [locale,changeLocale]=useState<Locale>(getLocale());setLocale(locale)
  if (!user || !session.token()) return <Login onLogin={setUser} locale={locale} changeLocale={changeLocale}/>
  return <Workspace user={user} locale={locale} changeLocale={changeLocale} onLogout={() => { session.clear(); setUser(null) }} />
}

function Login({ onLogin,locale,changeLocale }: { onLogin: (u: User) => void; locale:Locale; changeLocale:(l:Locale)=>void }) {
  const [email, setEmail] = useState('admin@curriva.local'), [password, setPassword] = useState('CurrivaAdmin!2026')
  const [busy, setBusy] = useState(false), [error, setError] = useState('')
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { const r = await api.login(email, password); onLogin(r.user) } catch (x) { setError(x instanceof Error ? x.message : 'Login failed') } finally { setBusy(false) } }
  return <main className="login-page"><section className="login-brand"><Logo/><div><span className="eyebrow">{tr('Recruitment intelligence')}</span><h1>{tr('Evidence-led hiring. Human-led decisions.')}</h1><p>{tr('Process CVs, discover talent, and understand every match in one secure workspace.')}</p></div><div className="login-trust"><ShieldCheck/><span><b>{tr('Private by design')}</b><small>Tenant-isolated candidate data and accountable workflows</small></span></div></section><section className="login-panel"><form className="login-card" onSubmit={submit}><LocalePicker locale={locale} change={changeLocale}/><span className="eyebrow">{tr('Welcome back')}</span><h2>{tr('Sign in to YazidCV')}</h2><p>{tr('Use your recruitment workspace credentials.')}</p>{error && <ErrorNotice message={error}/>}<label>{tr('Email address')}<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username"/></label><label>{tr('Password')}<input type="password" required value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label><button className="primary login-submit" disabled={busy}>{busy?<><LoaderCircle className="spin"/> {tr('Signing in…')}</>:<>{tr('Sign in securely')} <ArrowRight/></>}</button><small className="demo-note">Demo: admin@yazidcv.dev · YazidCV2026!</small></form></section></main>
}

function Workspace({ user,locale,changeLocale,onLogout }: { user: User;locale:Locale;changeLocale:(l:Locale)=>void;onLogout: () => void }) {
  const location=useLocation(), navigate=useNavigate(), [mobile,setMobile]=useState(false), [data,setData]=useState<ResourceState>(empty), [loading,setLoading]=useState(true), [error,setError]=useState(''), [modal,setModal]=useState<'candidate'|'job'|'upload'|null>(null), [selected,setSelected]=useState<Candidate|null>(null), [selectedJob,setSelectedJob]=useState<Job|null>(null), [editingCandidate,setEditingCandidate]=useState<Candidate|null>(null), [editingJob,setEditingJob]=useState<Job|null>(null)
  const load=useCallback(async()=>{setLoading(true);setError('');try{const [dashboard,candidates,jobs,reviews,cvs,integrations]=await Promise.all([api.dashboard(),api.candidates(),api.jobs(),api.reviews(),api.cvs(),api.integrations()]);setData({dashboard,candidates:candidates.content,jobs:jobs.content,reviews,cvs:cvs.content,integrations})}catch(x){setError(x instanceof Error?x.message:'Unable to load workspace')}finally{setLoading(false)}},[])
  useEffect(()=>{load();const unauthorized=()=>onLogout();window.addEventListener('yazidcv:unauthorized',unauthorized);return()=>window.removeEventListener('yazidcv:unauthorized',unauthorized)},[load,onLogout])
  useEffect(()=>{if(location.pathname==='/'||!paths.includes(location.pathname as Path))navigate('/dashboard',{replace:true})},[location.pathname,navigate])
  const go=(p:Path)=>{navigate(p);setMobile(false);setSelected(null);setSelectedJob(null)}
  const refresh=async()=>{await load();setModal(null);setEditingCandidate(null);setEditingJob(null);setSelected(null);setSelectedJob(null)}
  return <div className="app-shell">
    <AnimatePresence>{mobile&&<motion.div className="backdrop" onClick={()=>setMobile(false)} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}/>}</AnimatePresence>
    <aside className={mobile?'sidebar open':'sidebar'}>
      <div className="side-top"><Logo/><button className="icon-btn mobile-close" onClick={()=>setMobile(false)}><X/></button></div>
      <div className="workspace"><span className="workspace-avatar">CU</span><span><b>{user.organization}</b><small>{tr('Recruitment')}</small></span></div>
      <nav>{nav.map((g,i)=><div className="nav-group" key={i}>{g.section&&<span className="nav-label">{tr(g.section)}</span>}{g.items.map(x=><button key={x.path} onClick={()=>go(x.path)} className={location.pathname===x.path?'nav-item active':'nav-item'}><x.icon/><span>{tr(x.label)}</span>{x.path==='/review'&&data.reviews.length>0&&<em>{data.reviews.length}</em>}{x.path==='/jobs'&&data.dashboard&&<em>{data.dashboard.openJobs}</em>}</button>)}</div>)}</nav>
      <div className="sidebar-foot"><div className="system-health"><span className="pulse"/><div><b>{tr('API connected')}</b><small>{tr('Protected workspace')}</small></div></div><button className="profile" onClick={onLogout} title={tr('Sign out')}><span className="avatar">{user.firstName[0]}{user.lastName[0]}</span><span><b>{user.firstName} {user.lastName}</b><small>{user.role}</small></span><LogOut/></button></div>
    </aside>
    <main className="main"><header className="topbar"><button className="icon-btn menu-btn" onClick={()=>setMobile(true)}><Menu/></button><button className="global-search" onClick={()=>go('/search')}><Search/><span>{tr('Search candidates, skills, jobs…')}</span><kbd><Command/> K</kbd></button><div className="top-actions"><LocalePicker locale={locale} change={changeLocale} compact/><button className="icon-btn help" onClick={()=>window.open('http://localhost:18765/swagger-ui.html','_blank')} title="API documentation"><CircleHelp/></button><button className="icon-btn notification" onClick={()=>go('/review')} title="Review notifications"><Bell/>{data.reviews.length>0&&<i/>}</button><button className="primary small" onClick={()=>setModal('upload')}><Plus/> {tr('Add CV')}</button></div></header>
      <div className="page">{error&&<ErrorNotice message={error} action={load}/>} {loading?<Loading/>:selected?<CandidateDetail candidate={selected} back={()=>setSelected(null)} edit={()=>{setEditingCandidate(selected);setModal('candidate')}} archived={async()=>{await api.archiveCandidate(selected.id);setSelected(null);await load()}}/>:selectedJob?<JobDetail job={selectedJob} back={()=>setSelectedJob(null)} edit={()=>{setEditingJob(selectedJob);setModal('job')}}/>:<RouteContent path={location.pathname as Path} data={data} onCandidate={setSelected} onJob={setSelectedJob} modal={setModal} refresh={refresh}/>}</div>
    </main>
    <AnimatePresence>{modal==='upload'&&<UploadModal close={()=>setModal(null)} saved={refresh}/>} {modal==='candidate'&&<CandidateModal candidate={editingCandidate} close={()=>{setModal(null);setEditingCandidate(null)}} saved={refresh}/>} {modal==='job'&&<JobModal job={editingJob} close={()=>{setModal(null);setEditingJob(null)}} saved={refresh}/>}</AnimatePresence>
  </div>
}

function RouteContent({path,data,onCandidate,onJob,modal,refresh}:{path:Path;data:ResourceState;onCandidate:(c:Candidate)=>void;onJob:(j:Job)=>void;modal:(m:'candidate'|'job'|'upload')=>void;refresh:()=>Promise<void>}){
 if(path==='/candidates')return <CandidatesPage candidates={data.candidates} open={onCandidate} add={()=>modal('candidate')}/>
 if(path==='/jobs')return <JobsPage jobs={data.jobs} open={onJob} add={()=>modal('job')}/>
 if(path==='/search')return <SearchPage candidates={data.candidates} open={onCandidate}/>
 if(path==='/review')return <ReviewPage reviews={data.reviews} refresh={refresh}/>
 if(path==='/uploads')return <UploadsPage cvs={data.cvs} candidates={data.candidates} openCandidate={onCandidate} upload={()=>modal('upload')}/>
 if(path==='/reports')return <ReportsPage data={data}/>
 if(path==='/settings')return <SettingsPage integrations={data.integrations} refresh={refresh}/>
 if(path==='/admin')return <AdminPage/>
 return <Dashboard data={data} open={onCandidate}/>
}

function Logo(){return <div className="logo" aria-label="Curriva by Yasmid Studio"><span className="logo-mark"><span>C</span></span><span>Curri<span className="logo-accent">va</span></span></div>}
function PageHeading({eyebrow,title,subtitle,action}:{eyebrow?:string;title:string;subtitle:string;action?:React.ReactNode}){const element=isValidElement<{onClick?:()=>void}>(action)&&action.type==='button'&&!action.props.onClick?cloneElement(action,{onClick:()=>window.location.reload()}):action;return <div className="page-heading"><div>{eyebrow&&<span className="eyebrow">{tr(eyebrow)}</span>}<h1>{tr(title)}</h1><p>{tr(subtitle)}</p></div>{element}</div>}
function ErrorNotice({message,action}:{message:string;action?:()=>void}){return <div className="error-notice" role="alert"><CircleAlert/><span>{tr(message)}</span>{action&&<button onClick={action}><RefreshCw/> Retry</button>}</div>}
function Loading(){return <div className="loading-state"><LoaderCircle className="spin"/><h2>{tr('Loading your workspace')}</h2><p>{tr('Fetching protected recruitment data…')}</p></div>}

function Dashboard({data,open}:{data:ResourceState;open:(c:Candidate)=>void}){const d=data.dashboard!;return <><PageHeading eyebrow={new Intl.DateTimeFormat('en',{weekday:'long',day:'numeric',month:'long'}).format(new Date())} title="Good morning, Yazid" subtitle="Here’s what needs your attention across the hiring team." action={<button className="secondary"><span className="live-dot"/> Live data</button>}/><section className="metrics-grid"><Metric icon={BriefcaseBusiness} value={String(d.openJobs)} label="Open roles" note="Actively accepting candidates"/><Metric icon={UsersRound} value={String(d.activeCandidates)} label="Active candidates" note={`${d.candidatesThisWeek} added this week`}/><Metric icon={FileCheck2} value={String(d.awaitingReview)} label="Awaiting review" note="Human verification required" alert={d.awaitingReview>0}/><Metric icon={Zap} value={`${Math.floor(d.averageProcessingSeconds/60)}m ${d.averageProcessingSeconds%60}s`} label="Avg. processing" note="Across completed CVs"/></section><section className="dashboard-grid"><div className="card activity-card"><CardHead title="Candidate activity" subtitle="Applications received this week"/><div className="chart-number"><b>{d.activity.reduce((n,x)=>n+x.applications,0)}</b><span>Live recruitment volume</span></div><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={d.activity} margin={{left:-18,right:8}}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#4d806c" stopOpacity={.28}/><stop offset="100%" stopColor="#4d806c" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e9ece7"/><XAxis dataKey="day" axisLine={false} tickLine={false}/><Tooltip/><Area type="monotone" dataKey="applications" stroke="#2f6b55" strokeWidth={2.5} fill="url(#fill)"/></AreaChart></ResponsiveContainer></div></div><div className="card attention-card"><CardHead title="Needs attention" subtitle="Live items waiting on your team"/><Attention icon={FileText} tone="amber" title={`${data.reviews.filter(x=>x.confidence<70).length} low-confidence CVs`} text="Manual field verification needed"/><Attention icon={UsersRound} tone="blue" title={`${data.reviews.length} open reviews`} text="Assigned to the recruitment team"/><Attention icon={ShieldCheck} tone="rose" title={`${d.failedProcessing} processing exceptions`} text="Inspect and retry when ready"/></div></section><section className="card table-card"><CardHead title="Top matching candidates" subtitle="Ranked by stored evidence score"/><CandidateTable data={data.candidates.slice(0,6)} open={open}/></section></>}
function Metric({icon:Icon,value,label,note,alert}:{icon:typeof Activity;value:string;label:string;note:string;alert?:boolean}){return <motion.div className="card metric" whileHover={{y:-3}}><div className="metric-icon"><Icon/></div><div className="metric-top"><b>{value}</b>{alert&&<span className="alert-pill">{tr('Action required')}</span>}</div><h3>{tr(label)}</h3><p>{tr(note)}</p></motion.div>}
function CardHead({title,subtitle}:{title:string;subtitle:string}){return <div className="card-head"><div><h2>{tr(title)}</h2><p>{tr(subtitle)}</p></div></div>}
function Attention({icon:Icon,tone,title,text}:{icon:typeof Activity;tone:string;title:string;text:string}){return <div className="attention-row"><span className={'attention-icon '+tone}><Icon/></span><div><b>{tr(title)}</b><p>{tr(text)}</p></div><ChevronRight/></div>}

function CandidateTable({data,open}:{data:Candidate[];open:(c:Candidate)=>void}){if(!data.length)return <Empty icon={UsersRound} title="No candidates yet" text="Add a candidate or upload a CV to start building your talent pool."/>;return <div className="table-scroll"><table><thead><tr><th>{tr('Candidates')}</th><th>{tr('Experience')}</th><th>Top skills</th><th>Match</th><th>Status</th><th/></tr></thead><tbody>{data.map((c,i)=><tr key={c.id} onClick={()=>open(c)}><td><div className="candidate-cell"><span className={'candidate-avatar '+tone(i)}>{c.initials}</span><div><b>{c.fullName}</b><small>{c.currentTitle}{c.currentCompany&&` · ${c.currentCompany}`}</small></div></div></td><td><b className="body-bold">{c.yearsExperience} yrs</b><small>{[c.city,c.country].filter(Boolean).join(', ')}</small></td><td><div className="skill-row">{c.skills.slice(0,3).map(s=><span key={s}>{s}</span>)}</div></td><td><div className="score"><span style={{'--score':c.matchScore+'%'} as React.CSSProperties}/><b>{c.matchScore}%</b></div></td><td><span className={'status '+c.status.toLowerCase().replace('_','-')}>{label(c.status)}</span></td><td><button className="icon-btn" aria-label={`Open ${c.fullName}`}><ChevronRight/></button></td></tr>)}</tbody></table></div>}
const tone=(i:number)=>['sage','blue','plum','amber'][i%4]; const label=(s:string)=>s.replaceAll('_',' ').toLowerCase().replace(/^./,x=>x.toUpperCase())

function CandidatesPage({candidates,open,add}:{candidates:Candidate[];open:(c:Candidate)=>void;add:()=>void}){const[q,setQ]=useState('');const list=useMemo(()=>candidates.filter(c=>(c.fullName+c.currentTitle+c.skills.join(' ')).toLowerCase().includes(q.toLowerCase())),[candidates,q]);return <><PageHeading eyebrow="Talent pool" title="Candidates" subtitle="Explore, review, and organize every candidate profile." action={<button className="primary" onClick={add}><Plus/> {tr('Add candidate')}</button>}/><div className="toolbar"><div className="input-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={tr('Search by name, role, skill…')}/></div><button className="secondary" onClick={()=>setQ('')}><Filter/> {tr('Clear filters')}</button></div><div className="card table-card"><div className="result-head"><p><b>{list.length} {tr('Candidates').toLowerCase()}</b></p><span>{tr('Tenant-scoped records')}</span></div><CandidateTable data={list} open={open}/></div></>}
function JobsPage({jobs,open,add}:{jobs:Job[];open:(j:Job)=>void;add:()=>void}){return <><PageHeading eyebrow="Recruitment" title="Open roles" subtitle="Track hiring progress and evidence for every role." action={<button className="primary" onClick={add}><Plus/> {tr('Create job')}</button>}/>{jobs.length?<div className="job-grid expanded">{jobs.map(j=><motion.button type="button" className="card job-card job-card-button" key={j.id} whileHover={{y:-3}} onClick={()=>open(j)}><div className="job-icon"><BriefcaseBusiness/></div><span className="open-label"><i/> {label(j.status)}</span><h3>{j.title}</h3><p>{j.department} · {j.location} · {label(j.workplaceType??'')}</p><div className="job-stats"><div><b>{j.candidateCount}</b><span>{tr('Candidates')}</span></div><div><b>{j.requiredSkills.length}</b><span>{tr('Required skills')}</span></div><div><b>{j.closingDate?Math.max(0,Math.ceil((new Date(j.closingDate).getTime()-Date.now())/86400000)):'—'}</b><span>{tr('Days to close')}</span></div></div><div className="skill-row">{j.requiredSkills.map(s=><span key={s}>{s}</span>)}</div><span className="job-view">View details <ArrowRight/></span></motion.button>)}</div>:<Empty icon={BriefcaseBusiness} title="No jobs yet" text="Create your first role to start building a candidate pipeline."/>}</>}
function SearchPage({candidates,open}:{candidates:Candidate[];open:(c:Candidate)=>void}){const[q,setQ]=useState(''),[list,setList]=useState(candidates),[busy,setBusy]=useState(false),[error,setError]=useState('');const search=useCallback(async(value:string)=>{setBusy(true);setError('');try{const page=await api.candidates(value);setList(page.content)}catch(x){setError(x instanceof Error?x.message:'Search failed')}finally{setBusy(false)}},[]);useEffect(()=>{const timer=setTimeout(()=>search(q),300);return()=>clearTimeout(timer)},[q,search]);return <><PageHeading eyebrow="Intelligent discovery" title="Find the evidence, not just keywords" subtitle="Search across structured profiles, experience, and skills."/><div className="search-hero"><Sparkles/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="e.g. Senior Java engineer with Kafka…"/><button className="primary" onClick={()=>search(q)}>{busy?<LoaderCircle className="spin"/>:<Search/>}{tr('Search')}</button><div className="semantic"><span className="toggle on"><i/></span><b>{tr('Structured search')}</b><span>Name, title, skills, and profile evidence</span></div></div>{error&&<ErrorNotice message={error}/>}<div className="card table-card"><div className="result-head"><p><b>{list.length} matches</b></p><span>Server-side tenant-safe search</span></div><CandidateTable data={list} open={open}/></div></>}

function ReviewPage({reviews,refresh}:{reviews:Review[];refresh:()=>Promise<void>}){const[working,setWorking]=useState(''),[error,setError]=useState('');async function act(id:string,status:string){setWorking(id);setError('');try{await api.updateReview(id,status);await refresh()}catch(x){setError(x instanceof Error?x.message:'Action failed')}finally{setWorking('')}}return <><PageHeading eyebrow="Human-in-the-loop" title="Review queue" subtitle="Validate uncertain extraction and keep candidate data trustworthy."/>{error&&<ErrorNotice message={error}/>}<div className="review-summary"><div><span className="ring">{reviews.length}</span><p><b>{tr('Waiting for review')}</b><small>{reviews.filter(x=>x.priority==='HIGH').length}</small></p></div><div><Clock3/><p><b>{Math.ceil(reviews.length*7/60)}h {(reviews.length*7)%60}m</b><small>{tr('Estimated workload')}</small></p></div><div><Activity/><p><b>{tr('Human controlled')}</b><small>{tr('No automated hiring decisions')}</small></p></div></div>{reviews.length?<div className="card review-list">{reviews.map((r,i)=><div className="review-item" key={r.id}><span className={'candidate-avatar '+tone(i)}>{r.initials}</span><div className="review-name"><b>{r.candidateName}</b><small>{r.reason} · {r.currentTitle}</small></div><span className={'priority p'+(r.priority==='HIGH'?0:r.priority==='MEDIUM'?1:2)}>{label(r.priority)}</span><div className="confidence"><small>Confidence</small><b>{r.confidence}%</b></div><div className="review-actions"><button className="secondary" disabled={working===r.id} onClick={()=>act(r.id,'IN_PROGRESS')}>{working===r.id?<LoaderCircle className="spin"/>:tr('Claim')}</button><button className="primary" disabled={working===r.id} onClick={()=>act(r.id,'APPROVED')}><Check/> {tr('Approve')}</button></div></div>)}</div>:<Empty icon={FileCheck2} title="Review queue complete" text="There are no pending extraction issues. Newly flagged CVs will appear here."/>}</>}

function UploadsPage({cvs,candidates,openCandidate,upload}:{cvs:CvDocument[];candidates:Candidate[];openCandidate:(c:Candidate)=>void;upload:()=>void}){return <><PageHeading eyebrow="Document processing" title="CV uploads" subtitle="Upload and inspect every immutable document record." action={<button className="primary" onClick={upload}><Upload/> {tr('Upload CVs')}</button>}/><button className="upload-banner" onClick={upload}><span><Upload/></span><div><h3>{tr('Choose CVs to begin')}</h3><p>PDF, DOC, or DOCX · Up to 20 MB each · Text CVs are parsed automatically</p></div><span className="secondary">{tr('Browse files')}</span></button><div className="card process-card"><CardHead title="Uploaded documents" subtitle="Private, checksum-verified CV files"/>{cvs.length?cvs.map(c=>{const candidate=candidates.find(x=>x.id===c.candidateId);return <div className="process-row expanded-process" key={c.id}><span className="file-icon"><FileText/></span><div><b>{c.originalFilename}</b><small>{formatBytes(c.fileSize)} · {new Date(c.uploadedAt).toLocaleString(getLocale())}</small>{c.processingError&&<em className="processing-error">{c.processingError}</em>}</div><span className={'status '+(c.status==='COMPLETED'?'shortlisted':c.status==='FAILED'?'failed':'in-review')}>{c.status==='COMPLETED'?<Check/>:<Clock3/>} {label(c.status)}</span>{candidate?<button className="secondary" onClick={()=>openCandidate(candidate)}>Open candidate <ArrowRight/></button>:<span className="processing-note">{c.status==='OCR_REQUIRED'?'OCR setup required':'No candidate created'}</span>}</div>}):<Empty icon={Upload} title="No CVs uploaded" text="Securely upload a PDF, DOC, or DOCX to start processing."/>}</div></>}
function ReportsPage({data}:{data:ResourceState}){const exportCsv=()=>{const rows=[['Candidate','Title','Experience','Status','Skills'],...data.candidates.map(c=>[c.fullName,c.currentTitle,String(c.yearsExperience),c.status,c.skills.join('; ')])];const csv=rows.map(r=>r.map(x=>`"${x.replaceAll('"','""')}"`).join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download=`yazidcv-candidates-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)};return <><PageHeading eyebrow="Recruitment intelligence" title="Reports" subtitle="Operational insights generated from current workspace data." action={<button className="primary" onClick={exportCsv}><Download/> Export candidates CSV</button>}/><div className="report-grid"><Report title="Candidate pipeline" value={String(data.candidates.length)} text="Active candidate profiles"/><Report title="Processing quality" value={String(data.cvs.length)} text="Immutable CV uploads"/><Report title="Review workload" value={String(data.reviews.length)} text="Pending human checks"/><Report title="Open opportunities" value={String(data.jobs.filter(j=>j.status==='OPEN').length)} text="Published job openings"/></div></>}
function Report({title,value,text}:{title:string;value:string;text:string}){return <div className="card report-card"><span className="report-icon"><BarChart3/></span><h3>{tr(title)}</h3><strong className="report-value">{value}</strong><p>{tr(text)}</p></div>}

function SettingsPage({integrations,refresh}:{integrations:IntegrationStatus[];refresh:()=>Promise<void>}){return <><PageHeading eyebrow="Settings" title="Integrations" subtitle="Connect approved recruitment platforms without exposing credentials." action={<button className="secondary" onClick={refresh}><RefreshCw/> {tr('Refresh status')}</button>}/><div className="integration-grid">{integrations.map(item=><section className="card integration-card" key={item.provider}><div className={'provider-logo '+item.provider.toLowerCase()}>{item.provider==='LINKEDIN'?'in':'i'}</div><div className="integration-main"><div className="integration-title"><h2>{item.name}</h2><span className={'integration-status '+(item.configured?'configured':'required')}>{item.configured?<Check/>:<CircleAlert/>}{tr(item.configured?'Configured':'Action required')}</span></div><p>{item.requirement}</p><div className="integration-security"><ShieldCheck/><span>Credentials are read from server environment variables and are never sent to the browser.</span></div></div><a className="secondary" href={item.onboardingUrl} target="_blank" rel="noreferrer">{tr('Start onboarding')} <ArrowRight/></a></section>)}</div><div className="card integration-note"><h3>Why approval is required</h3><p>LinkedIn and Indeed restrict recruitment APIs to approved ATS partners. YazidCV reports configuration readiness from the server and never simulates a successful connection.</p></div></>}

function LocalePicker({locale,change,compact=false}:{locale:Locale;change:(l:Locale)=>void;compact?:boolean}){return <label className={compact?'locale-picker compact':'locale-picker'}><Languages/><span>{compact?'':tr('Language')}</span><select aria-label={tr('Language')} value={locale} onChange={e=>change(e.target.value as Locale)}><option value="en">EN · English</option><option value="fr">FR · Français</option><option value="ar">AR · العربية</option></select></label>}

function CandidateDetail({candidate:c,back,edit,archived}:{candidate:Candidate;back:()=>void;edit:()=>void;archived:()=>Promise<void>}){const[busy,setBusy]=useState(false);return <><button className="back-button" onClick={back}><ArrowLeft/> {tr('Back to candidates')}</button><div className="candidate-hero"><span className="candidate-avatar large sage">{c.initials}</span><div><span className={'status '+c.status.toLowerCase().replace('_','-')}>{label(c.status)}</span><h1>{c.fullName}</h1><p>{c.currentTitle}{c.currentCompany&&` · ${c.currentCompany}`} · {[c.city,c.country].filter(Boolean).join(', ')}</p><div className="skill-row">{c.skills.map(s=><span key={s}>{s}</span>)}</div></div><div className="candidate-actions"><button className="secondary" onClick={edit}>Edit profile</button><button className="danger-button" disabled={busy} onClick={async()=>{if(confirm(`Archive ${c.fullName}?`)){setBusy(true);await archived()}}}>Archive</button></div></div><div className="detail-grid"><section className="card profile-card"><CardHead title="Professional profile" subtitle="Persisted candidate record"/><p>{c.professionalSummary||'—'}</p><h3>{tr('Contact and experience')}</h3><div className="profile-facts"><p><span>{tr('Email')}</span><b>{c.email||'—'}</b></p><p><span>{tr('Phone')}</span><b>{c.phone||'—'}</b></p><p><span>{tr('Experience')}</span><b>{c.yearsExperience}</b></p><p><span>{tr('Source')}</span><b>{label(c.source)}</b></p></div></section><aside><div className="card match-card"><span className="match-ring">{c.matchScore}<small>%</small></span><div><h3>{tr('Evidence score')}</h3><p>{tr('Stored match evidence for human review')}</p></div><hr/><MatchLine label="Overall evidence" value={c.matchScore}/><div className="disclaimer"><ShieldCheck/>{tr('This score supports human review and is not an automated hiring decision.')}</div></div></aside></div></>}
function JobDetail({job,back,edit}:{job:Job;back:()=>void;edit:()=>void}){return <><button className="back-button" onClick={back}><ArrowLeft/> Back to jobs</button><div className="candidate-hero"><span className="candidate-avatar large sage"><BriefcaseBusiness/></span><div><span className={'status '+job.status.toLowerCase()}>{label(job.status)}</span><h1>{job.title}</h1><p>{job.department} · {job.location} · {label(job.workplaceType??'')}</p></div><div className="candidate-actions"><button className="primary" onClick={edit}>Edit job</button></div></div><div className="detail-grid"><section className="card profile-card"><CardHead title="Job description" subtitle="Persisted recruitment opening"/><p>{job.description||'No description provided.'}</p><h3>{tr('Required skills')}</h3><div className="skill-row">{job.requiredSkills.map(s=><span key={s}>{s}</span>)}</div></section><aside><div className="card contact-card"><h3>Hiring details</h3><p><span>{tr('Candidates')}</span><b>{job.candidateCount}</b></p><p><span>{tr('Closing date')}</span><b>{job.closingDate?new Date(job.closingDate).toLocaleDateString(getLocale()):'—'}</b></p><p><span>Workplace</span><b>{label(job.workplaceType??'—')}</b></p></div></aside></div></>}
function MatchLine({label:txt,value}:{label:string;value:number}){return <div className="match-line"><span>{tr(txt)}</span><b>{value}%</b><i><em style={{width:value+'%'}}/></i></div>}

function CandidateModal({candidate,close,saved}:{candidate:Candidate|null;close:()=>void;saved:()=>Promise<void>}){const[busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const payload={firstName:f.get('firstName'),lastName:f.get('lastName'),email:f.get('email')||null,phone:f.get('phone')||null,currentTitle:f.get('currentTitle'),currentCompany:f.get('currentCompany')||null,city:f.get('city')||null,country:f.get('country')||null,yearsExperience:Number(f.get('yearsExperience')),status:f.get('status')||'NEW',professionalSummary:f.get('summary')||null,skills:String(f.get('skills')).split(',').map(x=>x.trim()).filter(Boolean)};try{candidate?await api.updateCandidate(candidate.id,payload):await api.createCandidate(payload);await saved()}catch(x){setError(x instanceof Error?x.message:'Unable to save candidate');setBusy(false)}}return <FormModal title={candidate?'Edit candidate':'Add candidate'} subtitle="Create a structured candidate profile." close={close} onSubmit={submit} busy={busy} error={error}><div className="form-grid"><Field name="firstName" label="First name" defaultValue={candidate?.firstName} required/><Field name="lastName" label="Last name" defaultValue={candidate?.lastName} required/><Field name="email" label="Email" type="email" defaultValue={candidate?.email}/><Field name="phone" label="Phone" defaultValue={candidate?.phone}/><Field name="currentTitle" label="Current title" defaultValue={candidate?.currentTitle} required/><Field name="currentCompany" label="Current company" defaultValue={candidate?.currentCompany}/><Field name="city" label="City" defaultValue={candidate?.city}/><Field name="country" label="Country" defaultValue={candidate?.country}/><Field name="yearsExperience" label="Years of experience" type="number" min="0" defaultValue={candidate?.yearsExperience??0} required/><label>Status<select name="status" defaultValue={candidate?.status??'NEW'}><option value="NEW">New</option><option value="IN_REVIEW">In review</option><option value="SHORTLISTED">Shortlisted</option><option value="INTERVIEW">Interview</option><option value="REJECTED">Rejected</option></select></label><Field name="skills" label="Skills, comma-separated" className="wide" defaultValue={candidate?.skills.join(', ')} required/><label className="wide">Professional summary<textarea name="summary" rows={3} defaultValue={candidate?.professionalSummary}/></label></div></FormModal>}
function JobModal({job,close,saved}:{job:Job|null;close:()=>void;saved:()=>Promise<void>}){const[busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const payload={title:f.get('title'),department:f.get('department'),location:f.get('location'),workplaceType:f.get('workplaceType'),description:f.get('description'),requiredSkills:String(f.get('skills')).split(',').map(x=>x.trim()).filter(Boolean),status:f.get('status'),closingDate:f.get('closingDate')||null};try{job?await api.updateJob(job.id,payload):await api.createJob(payload);await saved()}catch(x){setError(x instanceof Error?x.message:'Unable to save job');setBusy(false)}}return <FormModal title={job?'Edit job':'Create job'} subtitle="Publish an internal recruitment opening." close={close} onSubmit={submit} busy={busy} error={error}><div className="form-grid"><Field name="title" label="Role title" defaultValue={job?.title} required/><Field name="department" label="Department" defaultValue={job?.department}/><Field name="location" label="Location" defaultValue={job?.location}/><label>Workplace type<select name="workplaceType" defaultValue={job?.workplaceType??'HYBRID'}><option>HYBRID</option><option>REMOTE</option><option>ONSITE</option></select></label><Field name="closingDate" label="Closing date" type="date" defaultValue={job?.closingDate}/><label>Status<select name="status" defaultValue={job?.status??'OPEN'}><option>OPEN</option><option>DRAFT</option><option>PAUSED</option><option>CLOSED</option><option>ARCHIVED</option></select></label><Field name="skills" label="Required skills" className="wide" defaultValue={job?.requiredSkills.join(', ')} required/><label className="wide">Description<textarea name="description" rows={4} defaultValue={job?.description}/></label></div></FormModal>}
function UploadModal({close,saved}:{close:()=>void;saved:()=>Promise<void>}){const input=useRef<HTMLInputElement>(null),[files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');async function upload(){if(!files.length){setError('Choose at least one CV file');return}setBusy(true);setError('');try{await api.upload(files);await saved()}catch(x){setError(x instanceof Error?x.message:'Upload failed');setBusy(false)}}return <motion.div className="modal-wrap" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.div className="modal" initial={{scale:.97,y:15}} animate={{scale:1,y:0}}><div className="modal-head"><div><h2>Add or scan candidate CVs</h2><p>Files are validated, checksummed, extracted, and stored privately.</p></div><button className="icon-btn" onClick={close}><X/></button></div>{error&&<ErrorNotice message={error}/>}<button type="button" className="modal-drop" onClick={()=>input.current?.click()}><span><Upload/></span><h3>{files.length?`${files.length} file${files.length>1?'s':''} selected`:'Choose documents or camera scans'}</h3><p>{files.length?files.map(f=>f.name).join(', '):'PDF, DOC, DOCX, JPG, PNG or TIFF · maximum 20 MB each'}</p></button><input ref={input} hidden type="file" multiple accept=".pdf,.doc,.docx,.jpg,.jpeg,.png,.tif,.tiff,application/pdf,image/*" onChange={e=>setFiles(Array.from(e.target.files??[]))}/><div className="privacy-note"><ShieldCheck/><p><b>Private by design</b><span>Text is extracted locally. Docker includes English, French, and Arabic OCR.</span></p></div><div className="modal-actions"><button className="secondary" onClick={close}>{tr('Cancel')}</button><button className="primary" onClick={upload} disabled={busy}>{busy?<><LoaderCircle className="spin"/> Processing…</>:<><Upload/> Upload & process</>}</button></div></motion.div></motion.div>}
function FormModal({title,subtitle,close,onSubmit,busy,error,children}:{title:string;subtitle:string;close:()=>void;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;busy:boolean;error:string;children:React.ReactNode}){return <motion.div className="modal-wrap" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.form className="modal form-modal" onSubmit={onSubmit} initial={{scale:.97,y:15}} animate={{scale:1,y:0}}><div className="modal-head"><div><h2>{tr(title)}</h2><p>{tr(subtitle)}</p></div><button type="button" className="icon-btn" onClick={close}><X/></button></div>{error&&<ErrorNotice message={error}/>} {children}<div className="modal-actions"><button type="button" className="secondary" onClick={close}>{tr('Cancel')}</button><button className="primary" disabled={busy}>{busy?<><LoaderCircle className="spin"/> {tr('Saving…')}</>:<><Check/> {tr('Save')}</>}</button></div></motion.form></motion.div>}
function Field({label:txt,className,...props}:{label:string;className?:string}&React.InputHTMLAttributes<HTMLInputElement>){return <label className={className}>{tr(txt)}<input {...props}/></label>}
function Empty({icon:Icon,title,text}:{icon:typeof Activity;title:string;text:string}){return <div className="empty"><span><Icon/></span><h3>{tr(title)}</h3><p>{tr(text)}</p></div>}
function formatBytes(n:number){return n<1024*1024?`${Math.ceil(n/1024)} KB`:`${(n/1024/1024).toFixed(1)} MB`}
