export type Locale = 'en' | 'fr' | 'ar'

const fr: Record<string,string> = {
  'Overview':'Vue d’ensemble','Jobs':'Offres','Talent search':'Recherche de talents','CV uploads':'Dépôt de CV','Review queue':'File de révision','Reports':'Rapports','Settings':'Paramètres','Recruitment':'Recrutement','CV intelligence':'Intelligence CV',
  'Good morning, Yazid':'Bonjour, Yazid','Here’s what needs your attention across the hiring team.':'Voici les éléments qui nécessitent l’attention de votre équipe.','Live data':'Données en direct','Open roles':'Postes ouverts','Active candidates':'Candidats actifs','Awaiting review':'En attente de révision','Avg. processing':'Traitement moyen','Candidate activity':'Activité des candidats','Applications received this week':'Candidatures reçues cette semaine','Needs attention':'À traiter','Live items waiting on your team':'Éléments en attente de votre équipe','Top matching candidates':'Meilleurs candidats correspondants','Ranked by stored evidence score':'Classés selon les preuves enregistrées',
  'Candidates in this result':'Candidats dans ce résultat','Explore, review, and organize every candidate profile.':'Explorez, révisez et organisez chaque profil candidat.','Add candidate':'Ajouter un candidat','Search by name, role, skill…':'Rechercher par nom, poste, compétence…','Clear filters':'Effacer les filtres','Tenant-scoped records':'Données isolées par organisation',
  'Track hiring progress and evidence for every role.':'Suivez la progression et les preuves pour chaque poste.','Create job':'Créer une offre','Candidates':'Candidats','Required skills':'Compétences requises','Days to close':'Jours avant clôture','Find the evidence, not just keywords':'Trouvez les preuves, pas seulement les mots-clés','Search across structured profiles, experience, and skills.':'Recherchez dans les profils structurés, l’expérience et les compétences.','Search':'Rechercher','Structured search':'Recherche structurée','Exact, explainable profile matching':'Correspondance exacte et explicable','matches found':'correspondances trouvées','Sorted by evidence score':'Classés par score de preuve',
  'Human-in-the-loop':'Contrôle humain','Validate uncertain extraction and keep candidate data trustworthy.':'Validez les extractions incertaines et préservez la fiabilité des données.','Waiting for review':'En attente de révision','Estimated workload':'Charge estimée','Human controlled':'Contrôlé par l’humain','No automated hiring decisions':'Aucune décision d’embauche automatisée','Claim':'Prendre','Approve':'Approuver','Review queue complete':'File de révision terminée','There are no pending extraction issues. Newly flagged CVs will appear here.':'Aucun problème d’extraction en attente. Les nouveaux éléments apparaîtront ici.',
  'Document processing':'Traitement documentaire','Upload and inspect every immutable document record.':'Importez et inspectez chaque document immuable.','Upload CVs':'Importer des CV','Choose CVs to begin':'Choisissez des CV pour commencer','Browse files':'Parcourir','Uploaded documents':'Documents importés','Private, checksum-verified CV files':'CV privés vérifiés par empreinte','No CVs uploaded':'Aucun CV importé','Securely upload a PDF, DOC, or DOCX to start processing.':'Importez un PDF, DOC ou DOCX en toute sécurité.','Recruitment intelligence':'Intelligence de recrutement','Operational insights generated from current workspace data.':'Analyses opérationnelles issues des données actuelles.','Export candidates CSV':'Exporter les candidats en CSV','Candidate pipeline':'Pipeline candidats','Processing quality':'Qualité du traitement','Review workload':'Charge de révision','Open opportunities':'Opportunités ouvertes',
  'Professional profile':'Profil professionnel','Persisted candidate record':'Dossier candidat enregistré','Contact and experience':'Contact et expérience','Email':'E-mail','Phone':'Téléphone','Experience':'Expérience','Source':'Source','Evidence score':'Score de preuve','Stored match evidence for human review':'Preuves enregistrées pour révision humaine','Overall evidence':'Preuve globale','This score supports human review and is not an automated hiring decision.':'Ce score assiste la révision humaine et ne constitue pas une décision automatisée.','Back to candidates':'Retour aux candidats',
  'Integrations':'Intégrations','Connect approved recruitment platforms without exposing credentials.':'Connectez des plateformes approuvées sans exposer les identifiants.','Action required':'Action requise','Configured':'Configuré','Start onboarding':'Commencer l’intégration','Refresh status':'Actualiser','Language':'Langue','English':'Anglais','French':'Français','Arabic':'Arabe','Sign out':'Se déconnecter','API connected':'API connectée','Protected workspace':'Espace protégé','Add CV':'Ajouter un CV','Search candidates, skills, jobs…':'Rechercher candidats, compétences, offres…',
  'Welcome back':'Bon retour','Sign in to YazidCV':'Connexion à YazidCV','Use your recruitment workspace credentials.':'Utilisez les identifiants de votre espace de recrutement.','Email address':'Adresse e-mail','Password':'Mot de passe','Sign in securely':'Connexion sécurisée','Signing in…':'Connexion…','Private by design':'Confidentiel par conception','Evidence-led hiring. Human-led decisions.':'Recrutement fondé sur les preuves. Décisions humaines.','Process CVs, discover talent, and understand every match in one secure workspace.':'Traitez les CV, découvrez des talents et comprenez chaque correspondance dans un espace sécurisé.',
  'No candidates yet':'Aucun candidat','Add a candidate or upload a CV to start building your talent pool.':'Ajoutez un candidat ou importez un CV pour commencer.','No jobs yet':'Aucune offre','Create your first role to start building a candidate pipeline.':'Créez votre premier poste pour commencer.','Loading your workspace':'Chargement de votre espace','Fetching protected recruitment data…':'Récupération des données protégées…','Save':'Enregistrer','Saving…':'Enregistrement…','Cancel':'Annuler','Current title':'Poste actuel','First name':'Prénom','Last name':'Nom','City':'Ville','Country':'Pays','Years of experience':'Années d’expérience','Professional summary':'Résumé professionnel','Role title':'Intitulé du poste','Department':'Département','Location':'Lieu','Closing date':'Date de clôture','Description':'Description'
}

const ar: Record<string,string> = {
  'Overview':'نظرة عامة','Candidates':'المرشحون','Jobs':'الوظائف','Talent search':'البحث عن المواهب','CV uploads':'رفع السير الذاتية','Review queue':'قائمة المراجعة','Reports':'التقارير','Settings':'الإعدادات','Recruitment':'التوظيف','CV intelligence':'ذكاء السير الذاتية',
  'Good morning, Yazid':'صباح الخير، يزيد','Here’s what needs your attention across the hiring team.':'إليك ما يحتاج إلى انتباه فريق التوظيف.','Live data':'بيانات مباشرة','Open roles':'الوظائف المفتوحة','Active candidates':'المرشحون النشطون','Awaiting review':'بانتظار المراجعة','Avg. processing':'متوسط المعالجة','Candidate activity':'نشاط المرشحين','Applications received this week':'طلبات التوظيف هذا الأسبوع','Needs attention':'يحتاج إلى اهتمام','Live items waiting on your team':'عناصر تنتظر فريقك','Top matching candidates':'أفضل المرشحين تطابقاً','Ranked by stored evidence score':'مرتّب حسب الأدلة المسجلة',
  'Explore, review, and organize every candidate profile.':'استعرض وراجع ونظّم ملفات المرشحين.','Add candidate':'إضافة مرشح','Search by name, role, skill…':'البحث بالاسم أو الوظيفة أو المهارة…','Clear filters':'مسح عوامل التصفية','Tenant-scoped records':'بيانات معزولة حسب المؤسسة','Track hiring progress and evidence for every role.':'تابع تقدم التوظيف والأدلة لكل وظيفة.','Create job':'إنشاء وظيفة','Required skills':'المهارات المطلوبة','Days to close':'أيام حتى الإغلاق',
  'Find the evidence, not just keywords':'ابحث عن الأدلة، لا الكلمات فقط','Search across structured profiles, experience, and skills.':'ابحث في الملفات المنظمة والخبرات والمهارات.','Search':'بحث','Structured search':'بحث منظم','Exact, explainable profile matching':'مطابقة دقيقة وقابلة للتفسير','Sorted by evidence score':'مرتّب حسب درجة الأدلة','Human-in-the-loop':'إشراف بشري','Validate uncertain extraction and keep candidate data trustworthy.':'تحقق من الاستخراج غير المؤكد وحافظ على موثوقية البيانات.','Waiting for review':'بانتظار المراجعة','Estimated workload':'العمل المتوقع','Human controlled':'تحت إشراف بشري','No automated hiring decisions':'لا توجد قرارات توظيف آلية','Claim':'استلام','Approve':'موافقة','Review queue complete':'اكتملت قائمة المراجعة','There are no pending extraction issues. Newly flagged CVs will appear here.':'لا توجد مشاكل معلقة. ستظهر السير الجديدة هنا.',
  'Document processing':'معالجة المستندات','Upload and inspect every immutable document record.':'ارفع وافحص كل سجل مستند محفوظ.','Upload CVs':'رفع السير الذاتية','Choose CVs to begin':'اختر السير الذاتية للبدء','Browse files':'اختيار الملفات','Uploaded documents':'المستندات المرفوعة','Private, checksum-verified CV files':'سير ذاتية خاصة ومتحقق منها','No CVs uploaded':'لا توجد سير مرفوعة','Securely upload a PDF, DOC, or DOCX to start processing.':'ارفع ملف PDF أو DOC أو DOCX بأمان.','Recruitment intelligence':'ذكاء التوظيف','Operational insights generated from current workspace data.':'رؤى تشغيلية مبنية على بيانات مساحة العمل.','Export candidates CSV':'تصدير المرشحين CSV','Candidate pipeline':'مسار المرشحين','Processing quality':'جودة المعالجة','Review workload':'عبء المراجعة','Open opportunities':'الفرص المفتوحة',
  'Professional profile':'الملف المهني','Persisted candidate record':'سجل مرشح محفوظ','Contact and experience':'التواصل والخبرة','Email':'البريد الإلكتروني','Phone':'الهاتف','Experience':'الخبرة','Source':'المصدر','Evidence score':'درجة الأدلة','Stored match evidence for human review':'أدلة محفوظة للمراجعة البشرية','Overall evidence':'الأدلة الإجمالية','This score supports human review and is not an automated hiring decision.':'هذه الدرجة تساعد المراجعة البشرية وليست قرار توظيف آلياً.','Back to candidates':'العودة إلى المرشحين',
  'Integrations':'التكاملات','Connect approved recruitment platforms without exposing credentials.':'اربط منصات التوظيف المعتمدة دون كشف بيانات الاعتماد.','Action required':'إجراء مطلوب','Configured':'تم الإعداد','Start onboarding':'بدء الربط','Refresh status':'تحديث الحالة','Language':'اللغة','English':'الإنجليزية','French':'الفرنسية','Arabic':'العربية','Sign out':'تسجيل الخروج','API connected':'واجهة API متصلة','Protected workspace':'مساحة عمل محمية','Add CV':'إضافة سيرة','Search candidates, skills, jobs…':'البحث عن مرشحين أو مهارات أو وظائف…',
  'Welcome back':'مرحباً بعودتك','Sign in to YazidCV':'تسجيل الدخول إلى YazidCV','Use your recruitment workspace credentials.':'استخدم بيانات اعتماد مساحة التوظيف.','Email address':'البريد الإلكتروني','Password':'كلمة المرور','Sign in securely':'تسجيل دخول آمن','Signing in…':'جارٍ الدخول…','Private by design':'الخصوصية أساس التصميم','Evidence-led hiring. Human-led decisions.':'توظيف قائم على الأدلة. قرارات يقودها الإنسان.','Process CVs, discover talent, and understand every match in one secure workspace.':'عالج السير الذاتية واكتشف المواهب وافهم كل تطابق في مساحة آمنة.',
  'No candidates yet':'لا يوجد مرشحون','Add a candidate or upload a CV to start building your talent pool.':'أضف مرشحاً أو ارفع سيرة ذاتية للبدء.','No jobs yet':'لا توجد وظائف','Create your first role to start building a candidate pipeline.':'أنشئ أول وظيفة لبدء مسار المرشحين.','Loading your workspace':'جارٍ تحميل مساحة العمل','Fetching protected recruitment data…':'جارٍ جلب بيانات التوظيف المحمية…','Save':'حفظ','Saving…':'جارٍ الحفظ…','Cancel':'إلغاء','Current title':'المنصب الحالي','First name':'الاسم الأول','Last name':'اسم العائلة','City':'المدينة','Country':'البلد','Years of experience':'سنوات الخبرة','Professional summary':'الملخص المهني','Role title':'المسمى الوظيفي','Department':'القسم','Location':'الموقع','Closing date':'تاريخ الإغلاق','Description':'الوصف'
}

Object.assign(fr,{'Administration':'Administration','People and teams':'Utilisateurs et équipes','Administrators provision every company account and team membership.':'Les administrateurs créent chaque compte et gèrent les équipes.','Add team':'Ajouter une équipe','Register user':'Créer un utilisateur','Active users':'Utilisateurs actifs','Organization teams':'Équipes de l’organisation','Admin controlled':'Contrôlé par un administrateur','No public registration':'Aucune inscription publique','Company users':'Utilisateurs de l’entreprise','Recruiters and hiring managers with scoped access':'Recruteurs et responsables du recrutement avec accès contrôlé','User':'Utilisateur','Role':'Rôle','Team':'Équipe','Status':'Statut','Active':'Actif','Inactive':'Inactif','Deactivate user':'Désactiver l’utilisateur','Create a secure company account.':'Créez un compte d’entreprise sécurisé.','Create an organization team.':'Créez une équipe dans l’organisation.','Temporary password':'Mot de passe temporaire','Team name':'Nom de l’équipe','Hiring manager':'Responsable du recrutement'})
Object.assign(ar,{'Administration':'الإدارة','People and teams':'المستخدمون والفرق','Administrators provision every company account and team membership.':'ينشئ المسؤولون جميع حسابات المؤسسة ويديرون عضوية الفرق.','Add team':'إضافة فريق','Register user':'إنشاء مستخدم','Active users':'المستخدمون النشطون','Organization teams':'فرق المؤسسة','Admin controlled':'بإشراف المسؤول','No public registration':'لا يوجد تسجيل عام','Company users':'مستخدمو الشركة','Recruiters and hiring managers with scoped access':'مسؤولو التوظيف ومديرو التوظيف بصلاحيات محددة','User':'المستخدم','Role':'الدور','Team':'الفريق','Status':'الحالة','Active':'نشط','Inactive':'غير نشط','Deactivate user':'تعطيل المستخدم','Create a secure company account.':'أنشئ حساب شركة آمناً.','Create an organization team.':'أنشئ فريقاً داخل المؤسسة.','Temporary password':'كلمة مرور مؤقتة','Team name':'اسم الفريق','Hiring manager':'مدير التوظيف'})

let current: Locale = (localStorage.getItem('yazidcv_locale') as Locale) || 'en'
export function setLocale(locale:Locale){current=locale;localStorage.setItem('yazidcv_locale',locale);document.documentElement.lang=locale;document.documentElement.dir=locale==='ar'?'rtl':'ltr'}
export function getLocale(){return current}
export function tr(text:string){const branded=text.replaceAll('YazidCV','Curriva').replace('Evidence-led hiring. Human-led decisions.','Turn CVs into clear, reviewable candidate insight.');return current==='fr'?(fr[text]?.replaceAll('YazidCV','Curriva')??branded):current==='ar'?(ar[text]?.replaceAll('YazidCV','Curriva')??branded):branded}
