package dev.yazidcv.cv;

import org.springframework.stereotype.Component;
import java.time.*;
import java.time.temporal.ChronoUnit;
import java.util.*;
import java.util.regex.*;
import java.util.stream.Collectors;

@Component
public class CvProfileExtractor {
 private static final Set<String> HEADINGS=Set.of("SKILLS","COMPÉTENCES","LANGUAGES","LANGUES","PROFESSIONAL EXPERIENCE","EXPÉRIENCE PROFESSIONNELLE","ACADEMIC EDUCATION","FORMATION ACADÉMIQUE","CONTACT","CERTIFICATES","CERTIFICATS","TECHNICAL","TECHNIQUES","MANAGERIAL","MANAGÉRIALES","ACADEMIC PROJECTS","PROJETS ACADÉMIQUES","PERSONAL PROJECTS","PROJETS PERSONNELS");
 private static final List<String> SKILLS=List.of("Java","Spring Boot","C#",".NET","ASP.NET Core","JavaScript","TypeScript","React","React.js","Angular","Angular Material","Next.js","Node.js","Python","Django","Django REST Framework","Flask","PHP","Symfony","WordPress","Flutter","PyQt5","HTML","CSS","SQL","MySQL","PostgreSQL","SQL Server","SQLite","Docker","Git","GitHub","Azure DevOps","Postman","JUnit","Selenium","SonarQube","REST","UML","Agile","Scrum","Tailwind CSS","Groq AI","Zustand","Machine Learning");
 private static final Pattern EMAIL=Pattern.compile("[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}",Pattern.CASE_INSENSITIVE);
 private static final Pattern PHONE=Pattern.compile("(?:\\+?\\d[\\d .()/-]{7,}\\d)");
 private static final Pattern LINKEDIN=Pattern.compile("https?://(?:www\\.)?linkedin\\.com/in/[^\\s]+",Pattern.CASE_INSENSITIVE);
 private static final Pattern GITHUB=Pattern.compile("https?://(?:www\\.)?github\\.com/[^\\s]+",Pattern.CASE_INSENSITIVE);
 private static final Pattern LOCATION=Pattern.compile("(?im)^([\\p{L} '-]{2,40})\\s*-\\s*(MAROC|MOROCCO|FRANCE|CANADA|BELGIQUE|BELGIUM)\\s*$");
 private static final Pattern PROFILE=Pattern.compile("(?im)^(.{4,100}?(?:Engineer|Ingénieur|Developer|Développeur|Manager|Consultant|Architecte?))\\s*[–—-]");
 private static final Pattern CURRENT_ROLE=Pattern.compile("(?im)^((?:Full Stack Developer|Développeur Full Stack|Software Engineer|Ingénieur [^\\r\\n]+|Developer|Développeur|Manager|Consultant|Architecte?))\\s+(?:November|Novembre)\\s+\\d{4}\\s*-\\s*(?:Present|Présent)\\s*$");
 private static final Pattern CURRENT_COMPANY=Pattern.compile("(?im)^(?:Full Stack Developer|Développeur Full Stack|Software Engineer|Ingénieur [^\\r\\n]+|Developer|Développeur|Manager|Consultant|Architecte?)\\s+(?:November|Novembre)\\s+\\d{4}\\s*-\\s*(?:Present|Présent)\\s*\\R([^\\r\\n]+?)(?:\\s*-\\s*[\\p{L} '-]+)?\\s*$");
 private static final Pattern COMPANY_AFTER=Pattern.compile("(?im)^(?:Full Stack Developer|Développeur Full Stack|Software Engineer|Ingénieur[^\\r\\n]*)[^\\r\\n]*\\R([^\\r\\n]+?)\\s*-\\s*([\\p{L} '-]+)\\s*$");

 public ParsedProfile parse(String raw,String filename){String text=normalize(raw);String email=find(EMAIL,text),phone=find(PHONE,text),linkedin=find(LINKEDIN,text),github=find(GITHUB,text);String[] name=detectName(text,filename,linkedin);String title=detectTitle(text);String company=detectCompany(text);String[] location=detectLocation(text);List<String> skills=SKILLS.stream().filter(s->containsSkill(text,s)).distinct().toList();List<String> languages=detectLanguages(text);String education=collectLines(text,List.of("degree","diplôme","baccalaureate","baccalauréat","school","école","classes préparatoires"),8);String experience=collectExperience(text);String projects=collectProjects(text);int years=experienceYears(text);int confidence=confidence(name,email,phone,title,skills,education,experience);String summary=profileSummary(text,title);return new ParsedProfile(name[0],name[1],email,phone,title,company,location[0],location[1],years,summary,skills,linkedin,github,languages,education,experience,projects,confidence);}
 private String normalize(String s){return s.replace("\u0000","").replace('\u00a0',' ').replaceAll("[ \\t]+"," ").replaceAll("(?m)^ +| +$","").replaceAll("\\R{3,}","\n\n").trim();}
 private String[] detectName(String text,String filename,String linkedin){List<String> lines=text.lines().map(String::trim).filter(x->x.length()>=4&&x.length()<=70&&!HEADINGS.contains(x.toUpperCase(Locale.ROOT))&&!x.contains(":")&&!x.contains("@")).toList();for(String line:lines){if(line.matches("[\\p{Lu}][\\p{Lu} '-]+")&&line.split(" ").length>=2){String[] p=line.toLowerCase(Locale.ROOT).split(" ");if(p.length==4&&p[0].equals(p[2]))return new String[]{title(p[2]+" "+p[3]),title(p[0]+" "+p[1])};int mid=Math.max(1,p.length/2);return new String[]{title(String.join(" ",Arrays.copyOfRange(p,mid,p.length))),title(String.join(" ",Arrays.copyOfRange(p,0,mid)))};}}if(linkedin!=null){String slug=linkedin.substring(linkedin.indexOf("/in/")+4).replaceFirst("-\\w+$","");String[] p=slug.split("-");if(p.length>1)return new String[]{title(p[0]),title(String.join(" ",Arrays.copyOfRange(p,1,p.length)))};}String base=filename.replaceFirst("(?i)\\.(pdf|docx?|rtf)$","").replaceAll("[_-]+"," ");return new String[]{title(base),"Candidate"};}
 private String detectTitle(String text){Matcher current=CURRENT_ROLE.matcher(text);if(current.find())return cleanTitle(current.group(1));Matcher profile=PROFILE.matcher(text);return profile.find()?cleanTitle(profile.group(1)):"Candidate";}
 private String detectCompany(String text){Matcher current=CURRENT_COMPANY.matcher(text);if(current.find())return current.group(1).trim();Matcher m=COMPANY_AFTER.matcher(text);return m.find()?m.group(1).trim():null;}
 private String[] detectLocation(String text){Matcher m=LOCATION.matcher(text);if(!m.find())return new String[]{null,null};String country=switch(m.group(2).toUpperCase(Locale.ROOT)){case "MAROC","MOROCCO"->"Morocco";case "BELGIQUE","BELGIUM"->"Belgium";default->title(m.group(2));};return new String[]{title(m.group(1)),country};}
 private List<String> detectLanguages(String text){Map<String,String> names=Map.of("arabic","Arabic","arabe","Arabic","french","French","français","French","english","English","anglais","English");Set<String> found=new LinkedHashSet<>();for(var e:names.entrySet())if(Pattern.compile("(?im)^"+Pattern.quote(e.getKey())+"\\s*:").matcher(text).find())found.add(e.getValue());return List.copyOf(found);}
 private boolean containsSkill(String text,String skill){String flexible=Pattern.quote(skill).replace("\\Q \\E","\\s+");return Pattern.compile("(?iu)(?<![\\p{L}\\p{N}])"+flexible+"(?![\\p{L}\\p{N}])").matcher(text).find();}
 private String collectLines(String text,List<String> markers,int max){return text.lines().map(String::trim).filter(x->x.length()>4&&markers.stream().anyMatch(m->x.toLowerCase(Locale.ROOT).contains(m))).distinct().limit(max).collect(Collectors.joining("\n"));}
 private String collectExperience(String text){return text.lines().map(String::trim).filter(x->x.matches("(?i).*(developer|développeur|engineer|ingénieur).*\\d{4}.*")||x.matches("(?i).*(communication|prodware|SGGI).*-(?:\\s*)?(Marrakech|Casablanca).*")).distinct().limit(12).collect(Collectors.joining("\n"));}
 private String collectProjects(String text){List<String> out=new ArrayList<>();String[] lines=text.split("\\R");for(int i=0;i<lines.length;i++){String x=lines[i].trim();if(x.endsWith(":" )&&i+1<lines.length&&!HEADINGS.contains(x.replace(":","").toUpperCase(Locale.ROOT))&&lines[i+1].matches("(?i).*(java|python|react|django|flutter|next|javascript|typescript|php|css|sql).*"))out.add(x+" "+lines[i+1].trim());}return out.stream().distinct().limit(12).collect(Collectors.joining("\n"));}
 private int experienceYears(String text){Map<String,Integer> months=Map.ofEntries(Map.entry("january",1),Map.entry("janvier",1),Map.entry("march",3),Map.entry("mars",3),Map.entry("july",7),Map.entry("juillet",7),Map.entry("august",8),Map.entry("août",8),Map.entry("september",9),Map.entry("septembre",9),Map.entry("november",11),Map.entry("novembre",11));Pattern p=Pattern.compile("(?iu)(January|Janvier|March|Mars|July|Juillet|August|Août|September|Septembre|November|Novembre)\\s+(\\d{4})\\s*-\\s*(January|Janvier|March|Mars|July|Juillet|August|Août|September|Septembre|November|Novembre|Present|Présent)\\s*(\\d{4})?");Matcher m=p.matcher(text);long total=0;while(m.find()){YearMonth start=YearMonth.of(Integer.parseInt(m.group(2)),months.get(m.group(1).toLowerCase(Locale.ROOT)));YearMonth end=m.group(4)==null?YearMonth.now():YearMonth.of(Integer.parseInt(m.group(4)),months.get(m.group(3).toLowerCase(Locale.ROOT)));total+=Math.max(1,ChronoUnit.MONTHS.between(start,end)+1);}return (int)Math.min(80,Math.round(total/12.0));}
 private int confidence(String[] name,String email,String phone,String title,List<String> skills,String education,String experience){int score=20;if(!name[1].equals("Candidate"))score+=20;if(email!=null)score+=15;if(phone!=null)score+=10;if(!title.equals("Candidate"))score+=10;if(skills.size()>=5)score+=10;if(!education.isBlank())score+=8;if(!experience.isBlank())score+=7;return Math.min(100,score);}
 private String profileSummary(String text,String title){Matcher p=Pattern.compile("(?is)"+Pattern.quote(title)+"\\s*[–—-]\\s*(.{80,900}?)(?=\\R(?:Full Stack|Développeur|ACADEMIC|PROJETS|TECHNICAL|TECHNIQUES))").matcher(text);if(p.find())return (title+" — "+p.group(1)).replaceAll("\\s+"," ").trim();return title;}
 private String find(Pattern p,String text){Matcher m=p.matcher(text);return m.find()?m.group().trim():null;}private String cleanTitle(String s){return s.replaceAll("\\s+"," ").trim();}private String title(String s){return Arrays.stream(s.trim().split("\\s+")).map(x->x.isBlank()?x:Character.toUpperCase(x.charAt(0))+x.substring(1).toLowerCase(Locale.ROOT)).collect(Collectors.joining(" "));}
 public record ParsedProfile(String firstName,String lastName,String email,String phone,String currentTitle,String currentCompany,String city,String country,int yearsExperience,String summary,List<String> skills,String linkedinUrl,String githubUrl,List<String> languages,String education,String experience,String projects,int confidence){}
}
