package dev.yazidcv.cv;
import dev.yazidcv.identity.TenantContext; import org.springframework.beans.factory.annotation.Value; import org.springframework.data.domain.*; import org.springframework.http.*; import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken; import org.springframework.util.StringUtils; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import java.io.*; import java.nio.file.*; import java.security.*; import java.time.Instant; import java.util.*;
@RestController @RequestMapping("/api/v1/cvs") public class CvUploadController{
 private static final Set<String> TYPES=Set.of("application/pdf","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document","image/jpeg","image/png","image/tiff"); private final CvDocumentRepository repo; private final TenantContext tenant; private final CvProcessingService processing; private final Path root;
 public CvUploadController(CvDocumentRepository r,TenantContext t,CvProcessingService processing,@Value("${yazidcv.upload-directory}")String root)throws IOException{repo=r;tenant=t;this.processing=processing;this.root=Paths.get(root).toAbsolutePath().normalize();Files.createDirectories(this.root);}
 @PostMapping(consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public ResponseEntity<List<CvResponse>> upload(@RequestPart("files")List<MultipartFile> files,@RequestParam(required=false)UUID candidateId,JwtAuthenticationToken auth)throws Exception{if(files.isEmpty()||files.size()>20)throw new IllegalStateException("Upload between 1 and 20 files");UUID org=tenant.organizationId(auth);List<CvResponse> out=new ArrayList<>();for(var f:files){validate(f);byte[] bytes=f.getBytes();String checksum=HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));if(repo.existsByOrganizationIdAndChecksum(org,checksum))throw new IllegalStateException("This CV has already been uploaded");String clean=StringUtils.cleanPath(Objects.requireNonNull(f.getOriginalFilename())).replaceAll("[^a-zA-Z0-9._-]","_");String key=org+"/"+UUID.randomUUID()+"-"+clean;Path target=root.resolve(key).normalize();if(!target.startsWith(root))throw new IllegalStateException("Unsafe filename");Files.createDirectories(target.getParent());Files.write(target,bytes,StandardOpenOption.CREATE_NEW);var doc=repo.save(new CvDocument(org,candidateId,clean,key,f.getContentType(),bytes.length,checksum,auth.getName()));out.add(CvResponse.from(processing.process(doc.getId(),target)));}return ResponseEntity.status(201).body(out);}
 @GetMapping public Page<CvResponse> list(@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,JwtAuthenticationToken auth){return repo.findByOrganizationId(tenant.organizationId(auth),PageRequest.of(page,Math.min(size,100),Sort.by(Sort.Direction.DESC,"createdAt"))).map(CvResponse::from);}
 @GetMapping("/{id}/content") public ResponseEntity<org.springframework.core.io.Resource> content(@PathVariable UUID id,@RequestParam(defaultValue="inline")String disposition,JwtAuthenticationToken auth)throws IOException{var doc=repo.findByIdAndOrganizationId(id,tenant.organizationId(auth)).orElseThrow(()->new NoSuchElementException("CV not found"));Path file=root.resolve(doc.getStorageKey()).normalize();if(!file.startsWith(root)||!Files.isRegularFile(file))throw new NoSuchElementException("Stored CV file not found");var resource=new org.springframework.core.io.FileSystemResource(file);String mode="attachment".equalsIgnoreCase(disposition)?"attachment":"inline";return ResponseEntity.ok().contentType(MediaType.parseMediaType(doc.getContentType())).header(HttpHeaders.CONTENT_DISPOSITION,mode+"; filename*=UTF-8''"+java.net.URLEncoder.encode(doc.getOriginalFilename(),java.nio.charset.StandardCharsets.UTF_8).replace("+","%20")).header(HttpHeaders.CACHE_CONTROL,"private, no-store").body(resource);}
 @DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void delete(@PathVariable UUID id,JwtAuthenticationToken auth)throws IOException{var doc=repo.findByIdAndOrganizationId(id,tenant.organizationId(auth)).orElseThrow(()->new NoSuchElementException("CV not found"));Path file=root.resolve(doc.getStorageKey()).normalize();if(!file.startsWith(root))throw new IllegalStateException("Unsafe stored path");Files.deleteIfExists(file);repo.delete(doc);}
 private void validate(MultipartFile f){if(f.isEmpty())throw new IllegalStateException("Empty files are not accepted");if(!TYPES.contains(f.getContentType()))throw new IllegalStateException("Only PDF, DOC, DOCX, JPG, PNG, and TIFF CVs are accepted");String n=Objects.requireNonNullElse(f.getOriginalFilename(),"").toLowerCase();if(!(n.endsWith(".pdf")||n.endsWith(".doc")||n.endsWith(".docx")||n.endsWith(".jpg")||n.endsWith(".jpeg")||n.endsWith(".png")||n.endsWith(".tif")||n.endsWith(".tiff")))throw new IllegalStateException("The file extension is not supported");}
 public record CvResponse(UUID id,UUID candidateId,String originalFilename,String contentType,long fileSize,String status,String extractionMethod,String processingError,Instant uploadedAt,Instant completedAt){static CvResponse from(CvDocument d){return new CvResponse(d.getId(),d.getCandidateId(),d.getOriginalFilename(),d.getContentType(),d.getFileSize(),d.getStatus(),d.getExtractionMethod(),d.getProcessingError(),d.getCreatedAt(),d.getCompletedAt());}}
}
