package dev.yazidcv.review;
import dev.yazidcv.candidate.*; import dev.yazidcv.identity.TenantContext; import jakarta.validation.Valid; import jakarta.validation.constraints.Pattern; import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken; import org.springframework.web.bind.annotation.*; import java.time.Instant; import java.util.*;
@RestController @RequestMapping("/api/v1/reviews") public class ReviewController{
 private final ReviewRepository reviews; private final CandidateRepository candidates; private final TenantContext tenant; public ReviewController(ReviewRepository r,CandidateRepository c,TenantContext t){reviews=r;candidates=c;tenant=t;}
 @GetMapping public List<ReviewResponse> pending(JwtAuthenticationToken auth){UUID org=tenant.organizationId(auth);return reviews.findByOrganizationIdAndStatusOrderByCreatedAtAsc(org,"PENDING").stream().map(r->{var c=candidates.findByIdAndOrganizationId(r.getCandidateId(),org).orElseThrow();return ReviewResponse.from(r,c);}).toList();}
 @PatchMapping("/{id}") public ReviewResponse transition(@PathVariable UUID id,@Valid @RequestBody Transition req,JwtAuthenticationToken auth){UUID org=tenant.organizationId(auth);var r=reviews.findByIdAndOrganizationId(id,org).orElseThrow(()->new NoSuchElementException("Review task not found"));r.transition(req.status(),auth.getName(),req.notes());r=reviews.save(r);var c=candidates.findByIdAndOrganizationId(r.getCandidateId(),org).orElseThrow();return ReviewResponse.from(r,c);}
 public record Transition(@Pattern(regexp="IN_PROGRESS|APPROVED|CORRECTED|REJECTED|UNRESOLVED")String status,String notes){}
 public record ReviewResponse(UUID id,UUID candidateId,String candidateName,String initials,String currentTitle,String reason,int confidence,String priority,String status,Instant createdAt){static ReviewResponse from(ReviewTask r,Candidate c){return new ReviewResponse(r.getId(),c.getId(),c.getFirstName()+" "+c.getLastName(),(c.getFirstName().substring(0,1)+c.getLastName().substring(0,1)).toUpperCase(),c.getCurrentTitle(),r.getReason(),r.getConfidence(),r.getPriority(),r.getStatus(),r.getCreatedAt());}}
}
